print("----------------------------------------")
print("This is to explore the VS Code editor")
print("----------------------------------------")
print("Testing git commit changes")
print("----------------------------------------")