print("----------------------------------------")
print("This is to explore the VS Code editor")
print("----------------------------------------")
print("Testing git commit changes")
print("----------------------------------------")
print("This is to test local Git repo action")
print("----------------------------------------")
print("This is third change for GitHub from VS")
print("----------------------------------------")
print("This is 4th test for stop GitHub Auto")
print("----------------------------------------")
print("This is 5th test for stop GitHub Auto")
print("----------------------------------------")